### ISSUE TITLE
[Bug]: GCS crashes during stop record

### ISSUE THREAD

**Issue by ntlhui** [UCSD-E4E/radio_collar_tracker_gcs#40]
### Commit Hash

4fb6c7e

### Steps to Reproduce?

1. Install `radio_collar_tracker_dsp2` at revision d32ae421
2. Make the following edits:
```
e4e@e4e-upcore-3:~/radio_collar_tracker_dsp2$ git diff autostart/rctrun.py
diff --git a/autostart/rctrun.py b/autostart/rctrun.py
index 9c28657..f538dff 100644
--- a/autostart/rctrun.py
+++ b/autostart/rctrun.py
@@ -9,6 +9,7 @@ import json
 import glob
 import re
 import select
+import logging
 from radio_collar_tracker_dsp2 import PingFinder
 from enum import Enum, IntEnum
 import yaml
@@ -24,7 +25,7 @@ stop_threads = False

 output_dir = None
 testDir = "../testOutput"
-testGPS = True
+testGPS = False

 class GPS_STATES(IntEnum):
        get_tty = 0
@@ -64,6 +65,7 @@ class RCTRun:
         baud = int(self.get_var('GPS_baud'))
         serialPort = self.get_var('GPS_device')
         self.UIB_Singleton = UIBoard(serialPort, baud, testGPS)
+        logging.debug("RCTRun init: created UIB")
         self.cmdListener = None
         self.test = test
         self.tcpport = tcpport
@@ -79,9 +81,13 @@ class RCTRun:


         self.init_comms_thread.start()
+        logging.debug("RCTRun init: started comms thread")
         self.init_SDR_thread.start()
+        logging.debug("RCTRun init: started SDR thread")
         self.init_output_thread.start()
+        logging.debug("RCTRun init: started output thread")
         self.init_gps_thread.start()
+        logging.debug("RCTRun init: started GPS thread")

         self.doRun = True

@@ -92,6 +98,7 @@ class RCTRun:
     def initComms(self):
         if self.cmdListener is None:
             self.cmdListener = CommandListener(self.UIB_Singleton, self.tcpport)
+            logging.debug("CommandListener initialized")
             self.cmdListener.port.registerCallback(EVENTS.COMMAND_START, self.startReceived)
:...skipping...
diff --git a/autostart/rctrun.py b/autostart/rctrun.py
index 9c28657..f538dff 100644
--- a/autostart/rctrun.py
+++ b/autostart/rctrun.py
@@ -9,6 +9,7 @@ import json
 import glob
 import re
 import select
+import logging
 from radio_collar_tracker_dsp2 import PingFinder
 from enum import Enum, IntEnum
 import yaml
@@ -24,7 +25,7 @@ stop_threads = False

 output_dir = None
 testDir = "../testOutput"
-testGPS = True
+testGPS = False

 class GPS_STATES(IntEnum):
        get_tty = 0
@@ -64,6 +65,7 @@ class RCTRun:
         baud = int(self.get_var('GPS_baud'))
         serialPort = self.get_var('GPS_device')
         self.UIB_Singleton = UIBoard(serialPort, baud, testGPS)
+        logging.debug("RCTRun init: created UIB")
         self.cmdListener = None
         self.test = test
         self.tcpport = tcpport
@@ -79,9 +81,13 @@ class RCTRun:


         self.init_comms_thread.start()
+        logging.debug("RCTRun init: started comms thread")
         self.init_SDR_thread.start()
+        logging.debug("RCTRun init: started SDR thread")
         self.init_output_thread.start()
+        logging.debug("RCTRun init: started output thread")
         self.init_gps_thread.start()
+        logging.debug("RCTRun init: started GPS thread")

         self.doRun = True

@@ -92,6 +98,7 @@ class RCTRun:
     def initComms(self):
         if self.cmdListener is None:
             self.cmdListener = CommandListener(self.UIB_Singleton, self.tcpport)
+            logging.debug("CommandListener initialized")
             self.cmdListener.port.registerCallback(EVENTS.COMMAND_START, self.startReceived)
             self.cmdListener.port.registerCallback(EVENTS.COMMAND_STOP, self.stopRun)

@@ -111,7 +118,9 @@ class RCTRun:
             if not self.test:
                 meta_files = glob.glob(os.path.join(output_dir, 'RUN_*'))
                 if len(meta_files) > 0:
-                    run_num = int(re.sub("[^0-9]", "", sorted(meta_files)[-1])) + 1
+                    run_num = int(re.sub("[^0-9]", "", sorted(meta_files)[-1].replace(output_dir, ''))) + 1
+                    logging.debug("Run Num:")
+                    logging.debug(run_num)
                 else:
                     run_num = 1
             run_dir = os.path.join(output_dir, 'RUN_%06d' % (run_num))
@@ -132,23 +141,36 @@ class RCTRun:

             #TODO add dynamic sdr_record

-            if not self.test:
+            if True:
+                logging.debug("Enterring start pingFinder")
                 self.ping_finder = PingFinder()
-                self.ping_finder.gain = self.cmdListener.options.getOption("gain")
-                self.ping_finder.sampling_rate = self.cmdListener.options.getOption("sampling_freq")
-                self.ping_finder.center_frequency = self.cmdListener.options.getOption("center_freq")
+                logging.debug("Enterring start pingFinder1")
+                self.ping_finder.gain = self.cmdListener.options.getOption("SDR_gain")
+                logging.debug("Enterring start pingFinder2")
+                self.ping_finder.sampling_rate = self.cmdListener.options.getOption("SDR_samplingFreq")
+                logging.debug("Enterring start pingFinder3")
+                self.ping_finder.center_frequency = self.cmdListener.options.getOption("SDR_centerFreq")
+                logging.debug("Enterring start pingFinder4")
                 self.ping_finder.run_num = run_num
+                logging.debug("Enterring start pingFinder5")
                 self.ping_finder.enable_test_data = False
-                self.ping_finder.output_dir = self.cmdListener.options.getOption("output_dir")
-                self.ping_finder.ping_width_ms = self.cmdListener.options.getOption("ping_width_ms")
-                self.ping_finder.ping_min_snr = self.cmdListener.options.getOption("ping_min_snr")
-                self.ping_finder.ping_max_len_mult = self.cmdListener.options.getOption("ping_max_len_mult")
-                self.ping_finder.ping_min_len_mult = self.cmdListener.options.getOption("ping_min_len_mult")
-                self.ping_finder.target_frequencies = self.cmdListener.options.getOption("frequencies")
+                logging.debug("Enterring start pingFinder6")
+                self.ping_finder.output_dir = self.cmdListener.options.getOption("SYS_outputDir")
+                logging.debug("Enterring start pingFinder7")
+                self.ping_finder.ping_width_ms = self.cmdListener.options.getOption("DSP_pingWidth")
+                logging.debug("Enterring start pingFinder8")
+                self.ping_finder.ping_min_snr = self.cmdListener.options.getOption("DSP_pingSNR")
+                logging.debug("Enterring start pingFinder9")
+                self.ping_finder.ping_max_len_mult = self.cmdListener.options.getOption("DSP_pingMax")
+                logging.debug("Enterring start pingFinder10")
+                self.ping_finder.ping_min_len_mult = self.cmdListener.options.getOption("DSP_pingMin")
+                logging.debug("Enterring start pingFinder11")
+                self.ping_finder.target_frequencies = self.cmdListener.options.getOption("TGT_frequencies")

                 self.ping_finder.register_callback(self.UIB_Singleton.sendPing)

                 self.ping_finder.start()
+                logging.debug("Started pingFinder")



@@ -168,6 +190,8 @@ class RCTRun:

         if testGPS:
             self.UIB_Singleton.sensorState = GPS_STATES.rdy
+            logging.debug("Sensor State:")
+            logging.debug(self.UIB_Singleton.sensorState)
             return

         while not GPSInitialized:
@@ -348,8 +372,10 @@ class RCTRun:

 def main():
     global stop_threads
+    logging.basicConfig(filename='example.log', filemode='w', level=logging.DEBUG)
+    logging.debug("starting in main")
     stop_threads = False
     RCTRun(tcpport=9000)

 if __name__ == "__main__":
-    main()
\ No newline at end of file
+    main()
e4e@e4e-upcore-3:~/radio_collar_tracker_dsp2$ git status
On branch master
Your branch is ahead of 'origin/master' by 2 commits.
  (use "git push" to publish your local commits)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   autostart/UIB_instance.py
        modified:   autostart/rctrun.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        .vscode/launch.json

no changes added to commit (use "git add" and/or "git commit -a")
e4e@e4e-upcore-3:~/radio_collar_tracker_dsp2$ git diff autostart/UIB_instance.py
diff --git a/autostart/UIB_instance.py b/autostart/UIB_instance.py
index bb00abf..282d891 100644
--- a/autostart/UIB_instance.py
+++ b/autostart/UIB_instance.py
@@ -55,12 +55,14 @@ class UIBoard:
         '''
         if self.testMode:
             while self.run:
+                time.sleep(4)
                 try:
-                    lat = -117.23679
-                    lon = 32.88534
+                    lon = -117.23679
+                    lat = 32.88534
                     hdg = 0
                     date = datetime.datetime.now()
                     packet = rctVehiclePacket(lat, lon, 0, hdg, date)
+                    print(packet.lat, packet.lon)
                     self.handleSensorPacket(packet)
                     self.recentLoc = [lat, lon, 0]
                 except Exception as e:
@@ -80,8 +82,8 @@ class UIBoard:

                             yearString = "20" + dat[4:6]
                             day = datetime.date(int(yearString), int(dat[2:4]), int(dat[0:2]))
-                            time = datetime.time(int(tme[0:2]), int(tme[2:4]), int(tme[4:6]))
-                            date = datetime.datetime.combine(day, time)
+                            tim = datetime.time(int(tme[0:2]), int(tme[2:4]), int(tme[4:6]))
+                            date = datetime.datetime.combine(day, tim)

                             packet = rctVehiclePacket(lat, lon, 0, hdg, date)

e4e@e4e-upcore-3:~/radio_collar_tracker_dsp2$
```
3. Run firmware
4. Connect to payload
5. Start recording
6. Stop recording

### Observed Behavior

```
(rctGCS) C:\Users\e4e\Downloads\radio_collar_tracker_gcs-drone_based_MD\radio_collar_tracker_gcs-drone_based_MD\scripts>python rctGCS.py
2022-29-24 16:10:07.994: ERROR:rctGCS:MAVModel: Remote Exception: cannot join thread before it is started
NoneType: None
2022-29-24 16:10:07.995: ERROR:rctGCS:MAVModel: Remote Traceback: Traceback (most recent call last):
  File "/home/e4e/radio_collar_tracker_comms/RCTComms/comms.py", line 1123, in __receiver
    callback(packet=packet, addr=addr)
  File "/home/e4e/radio_collar_tracker_dsp2/.venv/lib/python3.7/site-packages/autostart/tcp_command.py", line 313, in _gotStopCmd
    self.UIBoard.stop()
  File "/home/e4e/radio_collar_tracker_dsp2/.venv/lib/python3.7/site-packages/autostart/UIB_instance.py", line 174, in stop
    self.listener.join()
  File "/usr/lib/python3.7/threading.py", line 1039, in join
    raise RuntimeError("cannot join thread before it is started")
RuntimeError: cannot join thread before it is started
NoneType: None
Traceback (most recent call last):
  File "C:\Users\e4e\Downloads\radio_collar_tracker_gcs-drone_based_MD\radio_collar_tracker_gcs-drone_based_MD\scripts\ui\display.py", line 458, in <lambda>
    self.__missionStatusBtn.clicked.connect(lambda:self.__startStopMission())
  File "C:\Users\e4e\Downloads\radio_collar_tracker_gcs-drone_based_MD\radio_collar_tracker_gcs-drone_based_MD\scripts\ui\display.py", line 188, in __startStopMission
    self._mavModel.stopMission(timeout=self.defaultTimeout)
  File "C:\Users\e4e\Downloads\radio_collar_tracker_gcs-drone_based_MD\radio_collar_tracker_gcs-drone_based_MD\scripts\rctCore.py", line 390, in stopMission
    raise RuntimeError('STOP NACKED')
RuntimeError: STOP NACKED

(rctGCS) C:\Users\e4e\Downloads\radio_collar_tracker_gcs-drone_based_MD\radio_collar_tracker_gcs-drone_based_MD\scripts>call conda deactivate

(base) C:\Users\e4e\Downloads\radio_collar_tracker_gcs-drone_based_MD\radio_collar_tracker_gcs-drone_based_MD\scripts>
```

### Desired Behavior

Payload stops recording, both client and server are configured to start again.

**Comment by ntlhui** [comment]
@ntlhui to reattempt on https://github.com/UCSD-E4E/radio_collar_tracker_dsp2/commit/9193745d2d2948d9dc26902521dd71dc5f0a52c1 and https://github.com/UCSD-E4E/radio_collar_tracker_gcs/commit/51e43618cae4b4140e9fbd0da3606ef93b51e455
