### ISSUE TITLE
[Bug]: Estimated Track Precision

### ISSUE THREAD

**Issue by ntlhui** [UCSD-E4E/radio_collar_tracker_gcs#51]
### Commit Hash

beab8b1e88ca75be4c485820905bc6e7446b4326

### Steps to Reproduce?

1. Set up target for other than 173.5 MHz
2. Run tests
3. Generate precision

### Observed Behavior

```
Traceback (most recent call last):
  File "D:\workspace\e4e\rct\radio_collar_tracker_gcs\scripts\ui\display.py", line 596, in <lambda>
    self.__btn_precision.clicked.connect(lambda:self._mavModel.EST_mgr.doPrecisions(173500000))
  File "D:\workspace\e4e\rct\radio_collar_tracker_gcs\scripts\ping.py", line 227, in doPrecisions
    estimator = self.__estimators[frequency]
KeyError: 173500000
```

### Desired Behavior

Select specific transmitter to estimate precisions on

**Comment by ntlhui** [comment]
Duplicates #45
