### ISSUE TITLE
[Bug]: Fail to load from web

### ISSUE THREAD

**Issue by ntlhui** [UCSD-E4E/radio_collar_tracker_gcs#52]
### Commit Hash

beab8b1e88ca75be4c485820905bc6e7446b4326

### Steps to Reproduce?

1. Load GCS
2. Expand the `Map Display Tools` menu
3. Click `Load from Web`

### Observed Behavior

```
Traceback (most recent call last):
  File "D:\workspace\e4e\rct\radio_collar_tracker_gcs\scripts\ui\display.py", line 966, in <lambda>
    btn_loadWebMap.clicked.connect(lambda:self.__loadWebMap())
  File "D:\workspace\e4e\rct\radio_collar_tracker_gcs\scripts\ui\display.py", line 1033, in __loadWebMap
    temp = WebMap(self.__holder, p1lat, p1lon,
  File "D:\workspace\e4e\rct\radio_collar_tracker_gcs\scripts\ui\map.py", line 935, in __init__
    self.addLayers()
  File "D:\workspace\e4e\rct\radio_collar_tracker_gcs\scripts\ui\map.py", line 1146, in addLayers
    self.pingLayer, self.pingRenderer = self.setupPingLayer()
  File "D:\workspace\e4e\rct\radio_collar_tracker_gcs\scripts\ui\map.py", line 1093, in setupPingLayer
    ramp = style.colorRamp(defaultColorRampNames[22])
IndexError: list index out of range
```

### Desired Behavior

GCS should load from OSM

**Comment by ntlhui** [comment]
First broken in e33962e68dd897f2b918ea3848c36a200fb8cfda

**Comment by ntlhui** [comment]
The problem seems to be that `QgsStyle.defaultStyle().colorRampNames()` yields an empty list.  This might be a problem with the underlying QGis install, as I'm not able to query any style information from the `QgsStyle.defaultStyle()` object.

**Comment by ntlhui** [comment]
Not observed in b7fea04f815d615406979134f4553bab09b8b5dd.  Closing
